-- Use test db
USE `spendwise_dev`;
-- Add three categories to the database
INSERT INTO `categories` (Id, categoryName)
VALUES
(1, 'Food'),
(2, 'Clothing'),
(3, 'Books'),
(4, 'Rent'),
(5, 'Utilities'),
(6, 'Transportation'),
(7, 'Healthcare'),
(8, 'Entertainment'),
(9, 'Travel'),
(10, 'Education'),
(11, 'Savings'),
(12, 'Investments'),
(13, 'Insurance'),
(14, 'Gifts'),
(15, 'Donations'),
(16, 'Subscriptions'),
(17, 'Personal Care'),
(18, 'Household Supplies'),
(19, 'Childcare'),
(20, 'Pet Care'),
(21, 'Electronics'),
(22, 'Furniture'),
(23, 'Office Supplies'),
(24, 'Fitness'),
(25, 'Beauty'),
(26, 'Groceries'),
(27, 'Dining Out'),
(28, 'Alcohol'),
(29, 'Tobacco'),
(30, 'Hobbies'),
(31, 'Games'),
(32, 'Music'),
(33, 'Movies'),
(34, 'Concerts'),
(35, 'Events'),
(36, 'Vacations'),
(37, 'Flights'),
(38, 'Hotels'),
(39, 'Car Rentals'),
(40, 'Public Transport'),
(41, 'Fuel'),
(42, 'Maintenance'),
(43, 'Parking'),
(44, 'Tolls'),
(45, 'Taxes'),
(46, 'Loans'),
(47, 'Credit Card Payments'),
(48, 'Bank Fees'),
(49, 'Legal Fees'),
(50, 'Miscellaneous'),
(51, 'Unknown');
