-- Use dev db
USE `spendwise_dev`;
-- Add three categories to the database
INSERT INTO `categories` (Id, categoryName)
VALUES
(1, 'food'),
(2, 'clothing'),
(3, 'books'),
(4, 'rent'),
(5, 'utilities'),
(6, 'transport'),
(7, 'healthcare'),
(8, 'entertainment'),
(9, 'travel'),
(10, 'education'),
(11, 'savings'),
(12, 'investments'),
(13, 'insurance'),
(14, 'gifts'),
(15, 'donations'),
(16, 'subscriptions'),
(17, 'personal care'),
(18, 'household'),
(19, 'childcare'),
(20, 'pets'),
(21, 'electronics'),
(22, 'furniture'),
(23, 'office'),
(24, 'fitness'),
(25, 'beauty'),
(26, 'groceries'),
(27, 'dining'),
(28, 'drinks'),
(29, 'delivery'),
(30, 'hobbies'),
(31, 'games'),
(32, 'music'),
(33, 'movies'),
(34, 'concerts'),
(35, 'events'),
(36, 'vacations'),
(37, 'flights'),
(38, 'hotels'),
(39, 'car rentals'),
(40, 'public transport'),
(41, 'fuel'),
(42, 'maintenance'),
(43, 'parking'),
(44, 'tolls'),
(45, 'taxes'),
(46, 'loans'),
(47, 'credit card payments'),
(48, 'bank'),
(49, 'legal'),
(50, 'miscellaneous'),
(51, 'unknown'),
(52, 'medicine'),
(53, 'restaurant');
