#!/usr/bin/env bash
# clone the spendwise helper dev repo and cd into it.
git clone https://github.com/josfam/spendwise-helper-dev.git
cd spendwise-helper-dev

# leave and cleanup files
echo "Done."
sleep 1
echo "Cleaning up files..."
sleep 1
cd ..
sudo rm -r spendwise-helper-dev
sudo rm set_up_everything
