#!/usr/bin/env bash
# clone the spendwise helper dev repo and cd into it.
git clone https://github.com/josfam/spendwise-helper-dev.git
cd spendwise-helper-dev

# install python packages, and create virtual env
./setup_python_things

# create a virtual environment, and drop the current shell into it
# remove the current venv if it exists
if [ -d spendwise-venv ]; then
	sudo rm -r spendwise-venv
fi

python3 -m venv spendwise-venv
source spendwise-venv/bin/activate

# install other python packages
pip install mysqlclient

# install project dependencies from the requirements file
wget https://raw.githubusercontent.com/Cnnb01/SpendWise/main/requirements.txt
pip install -r requirements.txt

# set up the databases and users
./setup_mysql_things

# leave the repo directory and cleanup all script-downloaded files
echo "Done."
echo "Cleaning up files..."
sleep 1
cd ..
sudo rm -r spendwise-helper-dev
sudo rm set_up_everything
